---
- name: Install nginx
  apt: pkg=nginx state=latest update_cache=true
- name: nginx running
  service: name=nginx state=started enabled=yes
- name: copy files to remove server
  template: src=index.html.j2 dest=/var/www/html/index.html
  notify: restart nginx
