---
  - name: Create a security group
    local_action: 
      module: ec2_group
      name: "{{ security_group }}"
      description: Security Group for webserver Servers
      vpc_id: vpc-33623156
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: basic_firewall
  - name: Create an ec2 instance
    ec2:
       key_name: "{{ keypair }}"
       #aws_access_key: "{{aws_access_key}}"
       #aws_secret_key: "{{aws_secret_key}}"
       #group_id: sg-4f92b82b
       group: "{{ security_group }}"
       instance_type: "{{ instance_type}}"
       image: "{{ ami }}"
       wait: true
       region: "{{ region }}"
       count: 1  # default
       count_tag:
          Name: Demo
       instance_tags:
          Name: Demo
       vpc_subnet_id: subnet-dc5247b9
       assign_public_ip: yes
    register: ec2
  - name: Add to hosts
    local_action: lineinfile
      dest="/home/ramon/ansible-test/hosts" 
      regexp={{ item.public_ip }}
      insertafter="[webserver]" line={{ item.public_ip }}
    with_items: ec2.instances
  - name: Wait for SSH
    local_action: wait_for
      host={{ item.public_ip }}
      port=22
      state=started
    with_items: ec2.instances
