---
- name: Create admin user
  user: 
    name=admin
    password= "{{ admin_password }}"
    state=present
    groups=sudo
    append=yes
    shell=/bin/bash
    uid=5001
    home=/home/admin

- name: Add admin authorized key
  authorized_key: user=admin key={{ pubkey }} state=present


- name: Create user user
  user:
    name=user
    password= "{{ user_password }}"
    state=present
    groups=sudo,www-data
    append=yes
    shell=/bin/bash
    uid=5002
    home=/home/user

- name: Add user authorized key
  authorized_key: user=user key={{ pubkey }} state=present
